Microverse Module One: Capstone Project
DannieMo/MicroverseModule1-Capstone-Project pull request #1
Opened 2021-08-13 22:42 UTC by DannieMo

This project contains the HTML, CSS, and JavaScript Capstone Project. Capstone Projects are done at the end of a module at Microverse, a remote tech institution.

This project is a two pages website built for an annual global conference: CEOs International Community Global Summit.

Read through my readme to get the full details, see images and even download the repo for this conference page website. 

Thank😄

2021-08-13 23:34 UTC, mimipeshy requested changes
## Hi @DannieMo  👋🏾 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
#### Highlights

- good job on the ui but lets make it better✔️ 
- good GitHub workflow ✔️ 
- not forming any linter errors ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](<https://microverse.zendesk.com/hc/en-us/articles/1500004088561>) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](<https://airtable.com/shrQAqnBwek5a0O0s>)._

2021-08-13 23:34 UTC, mimipeshy commented on README.md
> +
- [ ] Kindly submit a video presentation that contains a demo of the project, showing the pages in different screen sizes. Also, one thing you are proud of 😄 
- [ ] Kindly make use of  GitHub Pages to deploy the web pages. Ensure that the project is deployed properly, all pages, links, and images work as expected. Lastly, the link to the deployed project should be present in the README.

2021-08-13 23:34 UTC, mimipeshy commented on html/about.html
> +          /></a>
- [ ] The logo link in the footer section is broken, kindly fix it

2021-08-13 23:34 UTC, mimipeshy commented on html/index.html
> +          </div>
- [ ] The navbar items should be in a single line. The CIC campaign overlaps to the next line displacing news nav item ⏬ 
![ci](https://user-images.githubusercontent.com/33067256/129425717-a5b1f7f2-15ac-435e-bab2-9e3634387979.png)
Kindly work on this

2021-08-13 23:34 UTC, mimipeshy commented on html/index.html
> +
- [ ] The whole section in small mobile views of up to 550px, the information is squeezed. Kindly add margins and fix the height of the images ⬇️ 

![bn](https://user-images.githubusercontent.com/33067256/129426050-25757b74-68ac-4fbd-921b-2df1147b9f77.png)

- [ ] From html semantics, the whole section should be wrapped in an `article` tag

2021-08-13 23:34 UTC, mimipeshy commented on html/index.html
> +          </p>
- [ ] the footer in small mobile view overlaps to the container above. Kindly fix this ⬇️ 

![kl](https://user-images.githubusercontent.com/33067256/129426153-0b8a25b5-affe-429a-af09-8f3bf25ffb4a.png)

2021-08-13 23:34 UTC, mimipeshy commented on html/about.html
> +    </section>
- [ ] In this section on the desktop view the two bottom columns should be centered, in a horizontal line and have a gradient over them when a user hovers over the image in both mobile and desktop view. 

Clone | Original
------------ | -------------
![jh](https://user-images.githubusercontent.com/33067256/129426538-65d5237e-9f50-4f86-aaa7-7daa26ebee76.png) | ![km](https://user-images.githubusercontent.com/33067256/129426549-b868e105-43eb-4eeb-a3f3-3a4b86b6faf0.png)

2021-08-13 23:34 UTC, mimipeshy commented on html/about.html
> +      </div>
- [ ] The image is overflowing outside of the container in mobile view making a horizontal line in mobile view. Kindly fix this
![hj](https://user-images.githubusercontent.com/33067256/129426703-692efa12-41b0-4207-ad3d-b74fbf0b8975.png)

2021-08-13 23:34 UTC, mimipeshy commented on html/index.html
> +
- [ ] From html semantics, the whole section should be wrapped in an `article` tag

2021-08-14 20:23 UTC, dasileker requested changes
### **Hi @DannieMo** 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

- Kindly As the Previous TSE mentioned, you need to upload a video for the project where e you should present the project + a working live demo link.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-14 21:26 UTC, DannieMo commented
Hello sir, i have been done with my project hours ago but my network has
been very poor. I tried hosting my app using Netlify and Heroku but the
issues still persist because of my poor network. The network issue is from
my service providers and there's nothing much I can do from my  ends.

 It's almost midnight now: deadline is just a few minutes away. Pls help me
move on to the next phase of my Microverse journey.

Thanks.

DannieMo



On Sat, 14 Aug 2021, 21:23 Zerradi Amine, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> *Hi @DannieMo <https://github.com/DannieMo>*
>
> Great work on making the changes requested by a previous reviewer 👏
> You've done well implementing some of the requested changes, but there are
> still some which aren't addressed yet.
> Required Changes ♻️
>
> *Check the comments under the review.*
> Optional suggestions
>
>    - Kindly As the Previous TSE mentioned, you need to upload a video for
>    the project where e you should present the project + a working live demo
>    link.
>
> *Every comment with the [OPTIONAL] prefix won't stop the approval of this
> PR. However, I strongly recommend you to take them into account as they can
> make your code better. Some of them were simply missed by the previous
> reviewer and addressing them will really improve your application.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/DannieMo/MicroverseModule1-Capstone-Project/pull/1#pullrequestreview-730130781>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AM3CJCAMZ7D5PBWUX5Y3UNDT43GFFANCNFSM5CEMV3OA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&utm_campaign=notification-email>
> .
>

2021-08-14 21:42 UTC, DannieMo commented
Still giving same response: page not found.

Pls help me.

Thanks

Dannie


On Sat, 14 Aug 2021, 22:36 netlify[bot], ***@***.***> wrote:

> ✔️ Deploy Preview for *thirsty-brahmagupta-217cae* ready!
>
> 🔨 Explore the source changes: 1591f21
> <https://github.com/DannieMo/MicroverseModule1-Capstone-Project/commit/1591f2105798361da1103c97dfb37e639f16d6a9>
>
> 🔍 Inspect the deploy log:
> https://app.netlify.com/sites/thirsty-brahmagupta-217cae/deploys/6118373e4558c1000878d696
> <https://app.netlify.com/sites/thirsty-brahmagupta-217cae/deploys/6118373e4558c1000878d696?utm_source=github&utm_campaign=bot_dl>
>
> 😎 Browse the preview:
> https://deploy-preview-1--thirsty-brahmagupta-217cae.netlify.app
> <https://deploy-preview-1--thirsty-brahmagupta-217cae.netlify.app?utm_source=github&utm_campaign=bot_dp>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/DannieMo/MicroverseModule1-Capstone-Project/pull/1#issuecomment-898961481>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AM3CJCEHPXOSXWHSD6QGYPTT43OWRANCNFSM5CEMV3OA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&utm_campaign=notification-email>
> .
>

2021-08-14 21:55 UTC, DannieMo commented
I just sent the loom presentation video now. Pls check it and let me know
what you think.

I really want to move on to the next phase of Microverse. Pls help me.

Thanks.

Dannie

On Sat, 14 Aug 2021, 22:42 Daniel Majesty Owiri, ***@***.***>
wrote:

> Still giving same response: page not found.
>
> Pls help me.
>
> Thanks
>
> Dannie
>
>
> On Sat, 14 Aug 2021, 22:36 netlify[bot], ***@***.***> wrote:
>
>> ✔️ Deploy Preview for *thirsty-brahmagupta-217cae* ready!
>>
>> 🔨 Explore the source changes: 1591f21
>> <https://github.com/DannieMo/MicroverseModule1-Capstone-Project/commit/1591f2105798361da1103c97dfb37e639f16d6a9>
>>
>> 🔍 Inspect the deploy log:
>> https://app.netlify.com/sites/thirsty-brahmagupta-217cae/deploys/6118373e4558c1000878d696
>> <https://app.netlify.com/sites/thirsty-brahmagupta-217cae/deploys/6118373e4558c1000878d696?utm_source=github&utm_campaign=bot_dl>
>>
>> 😎 Browse the preview:
>> https://deploy-preview-1--thirsty-brahmagupta-217cae.netlify.app
>> <https://deploy-preview-1--thirsty-brahmagupta-217cae.netlify.app?utm_source=github&utm_campaign=bot_dp>
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/DannieMo/MicroverseModule1-Capstone-Project/pull/1#issuecomment-898961481>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AM3CJCEHPXOSXWHSD6QGYPTT43OWRANCNFSM5CEMV3OA>
>> .
>> Triage notifications on the go with GitHub Mobile for iOS
>> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
>> or Android
>> <https://play.google.com/store/apps/details?id=com.github.android&utm_campaign=notification-email>
>> .
>>
>

2021-08-14 22:05 UTC, dasileker approved these changes
### **Hi @DannieMo** 

### **Project Approved ✅✅**

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚢
Congratulations! 🎉 

### **Optional**

- For the  Live demo link you can use the [rawgithag.com](https://raw.githack.com/) by selecting the html file link  like yours for example: [https://github.com/DannieMo/MicroverseModule1-Capstone-Project/blob/features/html/index.html] and paste it then take the dev link or the production link. now you have your lie demo

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-14 22:09 UTC, merged